# Generated by Django 4.1 on 2023-04-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='assigned_user',
            new_name='user',
        ),
    ]
