# Generated by Django 4.1 on 2023-04-24 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bugs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bugs',
            new_name='Bug',
        ),
    ]
