# Generated by Django 4.1 on 2023-04-24 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_bugs_bug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('requiremnt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.requirements')),
            ],
        ),
    ]
