# Generated by Django 4.1 on 2023-04-24 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_taskplanner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskplanner',
            old_name='requiremnt',
            new_name='requirement',
        ),
    ]
