# Generated by Django 4.1 on 2023-04-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_requiremnt_taskplanner_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reviewed', models.DateTimeField()),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
